SHEL-74-Pet-list-Page
Pelter-Team/Pelter-Frontend pull request #12
Opened 2024-11-13 19:02 UTC by ppearyxx

*not done yet*
*ps : i bomb my past by reopen branch because i do bad practice but the code still with me I copy it yet*

2024-11-16 16:02 UTC, TGRZiminiar commented on src/app/(user)/petlist/page.tsx
Move the code from `page.tsx` (server-side) to `CPage.tsx` (client-side). 
Vercel requires page.tsx to remain server-side for successful deployment. 
Currenly page.tsx is client side so when build on Vercel it will fail
@ppearyxx

2024-11-16 17:53 UTC, TGRZiminiar requested changes

2024-11-16 17:55 UTC, wit03 commented on src/features/user/components/FilterDrawer.tsx
> +  const [petTypes, setPetTypes] = useState({
Don't need to set object the default value, create type and cast type from the type of state you've created.

2024-11-16 18:53 UTC, ppearyxx commented on src/app/(user)/petlist/page.tsx
ok

2024-11-16 19:21 UTC, ppearyxx commented on src/app/(user)/petlist/page.tsx
> +  const [selectedTag, setSelectedTag] = useState("all")
okk

2024-11-16 19:25 UTC, ppearyxx commented on src/features/user/components/FilterDrawer.tsx
> +  const [petTypes, setPetTypes] = useState({
okkk

2024-11-17 02:53 UTC, ppearyxx commented on src/app/(user)/petlist/page.tsx
<img width="302" alt="Screenshot 2567-11-17 at 09 53 27" src="https://github.com/user-attachments/assets/afcc1405-63c4-4676-8867-5ab045e7c0f8">
 isn't it like this?

2024-11-17 03:22 UTC, ppearyxx commented
done all comment aa can u check @wit03 @TGRZiminiar

2024-11-17 14:15 UTC, TGRZiminiar commented on src/features/user/components/SortDropdown.tsx
> +  }
Here another duplicate sort

2024-11-19 11:14 UTC, ppearyxx commented
have fix it all but still have 3 red lines left. no idea with it ,but will find way

2024-11-19 17:04 UTC, merged